full_name = "Ashraf Fouda"
description = "Software Engineer with passion in new technologies, love every thing that is realy new and challenging."
why_threefold = "Threefold is changing the world by decentralizing and neutralizing the internet"
function = "Engineer"
rank = 0
project_ids = [-1]
contribution_ids = [-1]
nationality = "Egyptian"
