full_name = "Jan de Landtsheer"
description = "Jan has tons of experience in multiple fields, but feels he excels most when it comes to networking and data transmission."
why_threefold = "I believe ThreeFold has something could dramatically change the world for the better."
function = "Head of Research & Development"
linkedin= ""
rank = 0
project_ids = [1,2]
contribution_ids = [6,6]
nationality = "Belgian"
  
