full_name = "Phil Horn"
description = "Philip is based in Munich Germany, 48 (in 2018). Studied chemistry and computer science, deeply involved in core Internet and IT technologies since 1990. As scientist at heart I’m always curious and try to be open minded. Founder of a handful of companies and passionately mentoring startups to create successful strategies and prepare them for funding and market entrance. Currently head of digitalization and innovation in EMEA for a large service provider. Solid background in all aspects of IT infrastructure but even more so in how to utilize it to achieve desired business outcomes, support strategic development and create sustainable ecosystems."
why_threefold = "I love ThreeFold because of its disruptive technology with groundbreaking design integrated into a great philosophy to democratize the Internet. It makes clever use of blockchain to back transactions and has security and data privacy deeply embedded and thus has more than just the potential to make the world a better place"
function = "Ambassador"
linkedin= "https://www.linkedin.com/in/hornphilip/"
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "German"
