full_name = "Justin Snyder"
description = "Justin is a founding advisor at DecentraNet. An entrepreneur, attorney, and leading designer, Justin uses sound business practices and smart design aesthetics to create impactful experiences for brands, products, and events. He works with companies in the blockchain, sustainability, entertainment, digital collectibles, and e-commerce sectors, and is currently developing solutions to align technology, art, education, and spirituality. Justin holds a Juris Doctor in International Law from American University, Washington College of Law, and a Bachelor of Arts in Economics from West Virginia University."
why_threefold = "I fell in love with the ThreeFold project because the ripple effect for good is limitless! ThreeFold can help humanity co-create in a conscious and collaborative way enabling a world where people dream, innovate and connect in an inclusive, neutral and open-source environment, the way the internet was originally designed to be! "
function = "Product Coordinator"
linkedin= "https://www.linkedin.com/in/jus10snyder/"
rank = 0
project_ids = [1]
contribution_ids = [1,3]
nationality = "USA"
