full_name = "Rana Hassan"
description = "Rana is an enthusiastic Computer Engineer with a passion in learning and development. She enjoys a good cup of coffee and exploring new technologies."
why_threefold = "Threefold's innovattion bring great technology and new ideas to the world. Being a part of that is definetly a lifechanging experience."
function = "Engineer"
linkedin= "https://www.linkedin.com/in/rana-tarek-81310763/"
rank = 0
project_ids = [1,8]
contribution_ids = [6,6]
nationality = "Egyptian"
