full_name = "Hamdy Farag"
description = "Somone who is searching for some truths inside and outside"
why_threefold = "Threefold is building a new market around capacity which addresses some of the global issues like user security and prices, and allows for other submarkets to emerge as well.On a personal level Threefold is the best places I've ever worked for and that helped me to grow personally and meet amazing people, so it's a kind of place that changes your personality so you can do more changes to the world!"
function = "Engineer"
linkedin= "https://www.linkedin.com/in/hamdy/"
rank = 0
project_ids = [1,8]
contribution_ids = [6,6]
nationality = "Egyptian"
