full_name = "Ahmed Elsayed"
description = "Software Engineer @ Codescalers Egypt"
why_threefold = "I want to be one of the contributors to build the new neutral internet"
function = "Engineer"
linkedin= "https://www.linkedin.com/in/ahmedelsayed93/"
rank = 0
project_ids = [-1]
contribution_ids = [-1]
nationality = "Egyptian"
