full_name = "Ehab Hassan"
description = "I am a person who is positive about every aspect of lifes."
why_threefold = "I dream about a world where everyone can be happy"
function = "Senior Graphic Designer & Webdeveloper"
linkedin= ""
rank = 0
project_ids = [1,8]
contribution_ids = [6,6]
nationality = "Egyptian"
