full_name = "Kevin Louis Obeegadoo"
description = "Kevin enjoys 20+ years’ consulting across private and government sectors, on strategy, value creation, and assisting in structuring for international business, and is based in Mauritius since 2001. Having consulted across various business sectors including Automobile, Financial Services, FMCG, IT and Telecommunications, Media, Property Development & Management, he enjoys team‐working on game-changing projects, creating value, and moving businesses to new levels, while being committed to charitable and social endeavours."
why_threefold = "With a unique, realistic, and achievable solution to building a green, decentralised, distributed, and neutral IT infrastructure globally, committed to true values and charity, how can anyone not believe in the ThreeFold Foundation vision ?"
function = "Ambassador"
linkedin= ""
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "British - Mauritian"
