full_name = "Muhamad Azmy"
description = "A highly driven IT professional, and a perfection seeker."
why_threefold = "I get to contribute in making the world a better place, while in the same time making my self a better person and a better engineer. At three fold we always create new technologies which always excites me."
function = "Engineer"
linkedin= ""
rank = 0
project_ids = [1,8]
contribution_ids = [6,6]
nationality = "Egyptian"
