full_name = "Ali Chaddad"
description = "I have been working for Threefoold affiliates for three years developing software solutions"
why_threefold = "Threefold gives me the opportunity to be part of something bigger than me that has the potential to changee the world we live in."
function = "Software Engineer"
rank = 0
project_ids = [-1]
contribution_ids = [-1]
nationality = "Egyptian"
