full_name = "Christophe De Carvalho Pereira Martins"
description = "Christophe is a passionate developer that likes to travel the world. Trying to improve the world around him using technology is one of his goals. He is currently working for TF Tech and is involved in the 0-OS projects among other things."
why_threefold = "I joined Threefold cause I bielive the web needs to evolve into a more decentralized and faire network. Threefold is trying to create this new internet so that was my chance to contribute to this effort."
function = "Engineer"
linkedin= "https://www.linkedin.com/in/christophe-de-carvalho-pereira-martins-919504a1/"
rank = 0
project_ids = [1,2,17]
contribution_ids = [1,6,3]
nationality = "Belgian"
