full_name = "Chris Hutton"
description = "A serial entrepreneur and technology fanatic for 25 years now. Always researching tech trends and looking for new technologies to introduce to Africa. The continent of Africa is unique, to say the least, and the issues prohibiting growth and development are unique. Africa has proven its ability to leap frog a generation in technology with the rapid adoption of mobile telecommunications and its time to bring the new internet to this continent and watch how access to information creates equality and opportunity for Africa."
why_threefold = """To make a difference and leave this lifetime with the planet in a better state than when I arrived. Living is not enough... We all owe it to ourselves and to our children that we make a real contribution to society in our own lifetime and pave the way for a better future for those who follow."""
function = "Co-Founder"
linkedin= "https://www.linkedin.com/in/chris-hutton-a3034777/"
rank = 2
project_ids = [1,2]
contribution_ids = [6,6]
nationality = "South African"
