full_name = "Evon Yacoub"
description = "Experienced Office Manager with a demonstrated history of working in the computer software industry. Skilled in Human Resources, Management, Office Administration .. has Strong administrative professional"
why_threefold = "I dream about a world where everyone can be happy"
function = "Admin Coordinator"
linkedin= "https://www.linkedin.com/in/evon-yacoub-phri-b6028025/"
rank = 0
project_ids = [1,8]
contribution_ids = [6,3]
nationality = "Egyptian"
