full_name = "Milind Sathe"
description = "Extensive international experience in senior management positions with The Coca-Cola Company in managing operations in diverse emerging markets across continents. Proven track record in building organizational culture, multi-national leadership teams, coaching, mentoring and change management. Passionate about traveling, making friends, experiencing new cultures and cuisines."
why_threefold = "I believe ThreeFold Foundation’s idea holds great promise to empower local communities, develop much needed skills to face the challenges of the impending fourth industrial revolution and make businesses more competitive by making available low cost affordable digital resources."
function = "Ambassador"
linkedin= "https://www.linkedin.com/in/milind-sathe-336a0b68/"
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Indian"
