full_name = "Michel Coucke"
description = "Michel leads the CEO & Board Practice for Lancor, an executive search firm. Prior to founding Lancor, Michel was Co-Managing Partner of the Global Technology & Media Practice at Whitehead Mann, as well as setting up & managing the European Telecommunications & Internet Infrastructure Practice at Heidrick & Struggles, based in London. In his early career, he was Deputy MD of the Benelux countries for AT&T. Michel has a master’s degree in industrial engineering and biochemistry from Institut Meurice Engineering School Brussels and an executive master’s degree in management from Universite Libre de Bruxelles. He is also an AMP graduate from the IMD, Lausanne."
why_threefold = "ThreeFold is opening a new chapter. With the ThreeFold project we are contributing to the construction of a better world not just financially but globally. It is not just about another 'coin', it is a real revolution."
function = "Ambassador"
linkedin= "https://www.linkedin.com/in/michel-coucke-66112a/"
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Belgian"
