full_name = "Mihos Vasilopoulos"
description = "A serial entrepreuner: Co-Founder and until recently Executive Vice President of NEWAGE ENERGY, presently UK's largest private oil and gas company. Also co-Founder of Global Process Systems the leading Middle East fabricator of process modules, as well as co-Founder of HYDROCYCLONICS, a US based company developing water treatment systems. Previously held numerous Senior positions with KVAERNER (Head of Energy Asia), Executive Vice President of PETROPLUS, Advisor to the President of HYUNDAI HEAVY INDUSTRIES, Advisor to the Chairman of TRANSCANADA, and Senior Consultant with MARATHON OIL."
why_threefold = "The world is fast adopting e-currencies (against artificial FIAT); Backed by Capacity and supported by unique disruptive green technology, the TFT Token is a unique IT monetary instrument, that unlike other cryptocurrencies, has real value. In fact, ThreeFold Token is the pre-cursor of an exciting IT-created utility."
function = "Ambassador"
linkedin= ""
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Greek"
