full_name = "Weynand Kuijpers"
description = "Weynand is a rocket scientist that loves slingshotting new technologies into customer-centric orbits. He has been working with teams at the start of the internet and spent the celebration of the year 2000 sitting in a datacenter.  Nothing happened there and then but in the following years he developed a growing interest to help, optimise and simplify the world of IT. First follower, team player and very passionate about bringing equal opportunities to young talent around the world."
why_threefold = "For Weynand, the Internet is where the next generation will expand their minds and innovate. He experienced this first-hand when his son outsmarted him by learning online how to boil an egg in a microwave. Such learning ability should be available globally, sustainably and efficiently."
function = "co-founder"
linkedin= "https://www.linkedin.com/in/weynandkuijpers/"
rank = 5
project_ids = [1]
contribution_ids = [1]
nationality = " "
