full_name = "Ali Omari"
description = "Ali is the CEO of Safe City Group in Abu Dhabi, United Arab Emirates. 20 years of accumulative experience in the industry with a passion to concentrate on providing the latest technologies and solutions. "
why_threefold = "I believe in ThreeFold Foundation’s dream in helping the world to become a better place."
function = "Ambassador"
linkedin= "https://www.linkedin.com/in/eng-ali-omari-4703186b/"
rank = 0
project_ids = [1]
contribution_ids = [8]
nationality = "Emirati"
