full_name = "Lucia Groenfelt"
description = "Lucia has been working in Human Resources for most of her life and has a passion for getting things done the right way for the company, but certainly also for the individual. She's looking forward to bring this movement to the next level and get internet capacity in the hands of people that have had very poor access to it to date."
why_threefold = "ThreeFold's vision is an ambitious one: to create a neutral, private, efficient and affordable internet. ThreeFold's team has breakthrough technology that will create a new, distributed and accessible for anyone internet. The world is dying for an alternative to large, non-transparent and privacy-invading service providers of today. Equal chances for every one of us, not a happy few of us."
function = "Ambassador"
linkedin= ""
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Dutch"
