full_name = "DR. Mariza Wellesley-Wesley, LL.M."
description = """Born in Vienna 1961; Doctor of law (Vienna) and master of laws (Columbia university, NY), Rechtsanwalt (advocate) (retired); Professional career: Heller Loeber Bahn, vienna; Freshields, London; Chief Counsel at European Bank for Reconstruction and Development; international consultant in business and banking; COO Green Edeg Cloud Ltd, England; CEO Green Edge Cloud Austria; """
why_threefold = """I believe in a democtratic, private, secret, decentralised and distributed internet; I am excited about building a new network taht will solve many ills of the current monopolistic system."""
function = "Ambassador"
linkedin= ""
rank = 0
project_ids = [1, 2]
contribution_ids = [2, 3]
nationality = "Austrian"
