full_name = "Franco Sorgi"
description = "Born and raised in Italy, living in the USA, Citizen of the world, let's see what's next. Vice president of Fine Foods Solutions, food and service industry California, USA (currently). Director of operations 'Brandy Melville Canada', woman fashion and apparel, ontario Canada (currently). Blockchain believer, Bitcoin enthousiast, cryptocurrency fanatic."
why_threefold = "I strongly believe in decentralization, net neutrality, privacy, open source organizations, transparancy, equal distribution, and the freedom to connect to anyone in the world without any filter. But then again... I may be crazy! I believe that the ThreeFold Foundation falls exactly in the categories I just mentioned, thus I'd love to give my support."
function = "Ambassador"
linkedin= ""
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Italian/American"
