full_name = "Rob Tol"
description = "Rob is a passionate coach, qigong teacher and former tour professional golfer. He combines several disciplines and different fields of science in his coaching work. People are often touched by his stillness and inner peace or triggered by his sharp observations and straightforward messages that effortlessly uncover the essence of your being. In whatever way you come into contact with Rob, one thing is for sure: it will change your life."
why_threefold = "ThreeFold's intention of creating a self-healing, small-scaled but world wide Internet seamlessly fits my idea of 'One world, One mind'. As humans, we are already connected at a deep level. A level before ideas of separation and perceived differences. I see ThreeFold as a physical, real world reflection of this connectedness. A move towards unity and equality."
function = "Ambassador"
linkedin= "https://www.linkedin.com/in/rob-tol-634614101/"
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Dutch"
