full_name = "Mahmoud Ayoub"
description = "Mahmoud is a passionate Computer Scientist who loves exploring new areas in life and technology"
why_threefold = "because threefold is the future of technology"
function = "Software Engineer"
linkedin= "https://www.linkedin.com/in/dmahmou"
rank = 0
project_ids = [1,2]
contribution_ids = [6,6]
nationality = "Egyptian"
