full_name = "Atef Nazmy"
description = "IT-Telecom & Networking Engineer , having a great passion to learn more about new technologies" 
why_threefold = "I Believe that ThreeFold Foundation Drives the world to be Better and Greener "
function = "Cloud Admin"
rank = 0
project_ids = [1,8]
contribution_ids = [6,6]
nationality = "Egyptian"
