full_name = "Erik van der Meulen"
description = "Erik firmly believes that entrepreneurship provides the only sustainable solution to many of humanity's greatest challenges. He has been active as an entrepreneur for over 25 years and co-founded several succesful businesses. Some of these are united in Powered By Meaning, a growing ecosystem of companies that have one shared mission: make impact through collective entrepreneurship. Erik is passionate about conceiving and realising new creative business concepts that unite both social and economic value."
why_threefold = "The Treefold Foundation aims to solve some of the fundamental shortcomings of the technologies that shape our future. I strongly support the values and the goals of the team and am exited about the opportunity to support them as ambassador."
function = "Ambassador"
linkedin= ""
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Dutch"
