full_name = "Waleed Hammam"
description = "Waleed is a Software Engineer with great passion in Computer Science and new technologies"
why_threefold = "Threefold is the gate for our digital freedom that was never existed before, It gave me the chance to learn special technologies and has great people working there."
function = "Engineer"
rank = 0
project_ids = [1,8]
contribution_ids = [6,6]
nationality = "Egyptian"
