full_name = "Peter van der Henst"
description = "Peter is HR-manager and Financial Advisor For TF Tech. Besides that Peter is an entrepreneur active in the world of start-ups and scale-ups for about 8 years now. Next to running the best business center in Belgium, where he lets companies grow and develop themselves, he is Kristof’s financial guy for several interesting projects in Belgium, Spain & Egypt."
why_threefold = ""
function = "Co-Founder"
linkedin= ""
rank = 19
project_ids = [1,2,5]
contribution_ids = [1,1,1]
nationality = "Belgian"
