full_name = "Nicola Moresi"
description = "Nicola is a non-stop entrepreneur and connects technology concepts with business opportunities and growth capital. He builds business around technology. Data Center owner, Working on Cloud technologies since 2011, he master consulting and integration on the whole IT Scene."
why_threefold = "Finally with ThreeFold Foundation the positive impact that technology has on our life, can be brought in a neutral and secure way to all people around the world. Living in a Digital world where our life, our memories, our history is digital, the help of a secure and neutral Internet is the basis for building up our new distributed life."
function = "Ambassador"
linkedin= ""
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Swiss"
