full_name = "Josef Ehrenhoefer"
description = "Josef Ehrenhoefer - also called Pepo - is the founder and owner of consult2win and is a Certified Management Consultant focused on M&A implementations and Digital Transformation Projects. Previously Pepo was Vice President of Enterprise Services at HP, Hewlett Packard Enterprise and DXC Technology in Austria and Central & Eastern Europe. He has gained tremendous experience in successfully implementing complex, multi-country transformation projects."
why_threefold = "I'm very passionate and excited about the opportunities of Digital Transformation for our economies, societies and lifes. However it is obvious that the current System is heavily centralized and extremely tuned to the success of a few. ThreeFold Tech and Threefold Foundation are perfectly positioned to fundamentally transform the Status Quo and to better serve future internet demand and to benefit many - not just a few."
function = "Ambassador"
linkedin= "https://www.linkedin.com/in/josef-ehrenhoefer/"
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Austrian"
