full_name = "Kyle Weber"
description = "Kyle has spent the last 10 years working in/on sustainability projects ranging from large scale commercial solar farms to rural NGO tuberculosis control programs. He has worked on a number of startups and founder of EVERA, a Dubai-based organization trying to make mobility more sustainable. Everyday he tries very hard not to be an idiot, or take himself too seriously. Sometimes he is successful."
why_threefold = "I believe in ThreeFold Foundation because I believe in the people behind the movement."
function = "Ambassador"
linkedin= ""
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "American"
