full_name = "Bola E.Nasr"
description = "Software Engineer with a passion for everything new and challenging in life and technology."
why_threefold = "I strongly believe that the technology can help to create a better world and that is exactly the mission of the ThreeFold ,I find it very important for people to have equal chances, and a lot can be changed through technology these days."
function = "Engineer"
linkedin= ""
rank = 0
project_ids = [1,8]
contribution_ids = [6,6]
nationality = "Egyptian"
