full_name = "Marina Achillea"
description = "My name is Marina Achillea and I am a 36 year old fashion designer from Sweden working and living in London with my husband. I am proud to be reperesenting the ThreeFold foundatoin and look forward to exciting and changing times ahead"
why_threefold = "I believe that the internet should be a fundamental right for every person in the world. That belief is shared by the ThreeFold foundation in it’s quest to expand the reach of the web to every corner of the world."
function = "Ambassador"
linkedin= "https://www.linkedin.com/in/marina-achillea-94694040/"
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Swedish"
