full_name = "Sophie De Maesschalck"
description = "Sophie has over 10 years of experience in technology incubation, international financing and mergers and acquisitions. She is currently the CFO of ThreeFold Foundation, GIG Technology and GIG Holding. Besides ThreeFold Foundation, she is a partner and group CFO at Incubaid, one of the most disruptive incubators in the tech scene that has supported a portfolio of over 15 start-ups and successfully exited 6 companies to large, international corporations as Western Digital and Oracle. Sophie holds an MSc and PhD in Electrotechnical engineering from Ghent University (Belgium) and an MBA from Vlerick Business School (Belgium). Prior to working at ThreeFold, she held positions at Bain & Company, the management consultancy and Proximus, the leading Belgian mobile operator."
why_threefold = ""
function = ""
linkedin= "https://www.linkedin.com/in/sophiedemaesschalck/"
rank = 0
project_ids = []
contribution_ids = []
nationality = "Belgian"
