full_name = "Oscar Landman"
description = "Oscar is working in IT for 30 years, being active international for almost half the time. He has a Master in IT and professionally certified in several IT architecture directions, together with his sales experience, he combined a couple of interesting skills to add value. He worked for corporates for 10 years after which he started his own company, driving his own beliefs."
why_threefold = "ThreeFold to me, is a new-age organization (driven from love and believe instead of ego), combining a couple of true new technologies. With this global movement, it is time to start a new economy. An economy based on other values, where responsibility and going Green are key words."
function = "Ambassador"
linkedin= ""
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Dutch"
