full_name = "Michael Gaffney"
description = "Michael is extremely grateful to be serving as a ThreeFold ambassador and fully supports ThreeFold’s mission of a sustainable internet in the hands of the people. Michael believes in humanity’s inherent goodness and its willingness to help and lift others up –ThreeFold holds this view as well and challenges us to believe it can and will be accomplished. Michael is currently an information specialist with an energy policy think tank in Saudi Arabia and in his spare time is a fitness/calisthenics junkie and an avid traveler."
why_threefold = "What's not to love about a foundation that has the technological skill and know how to build a new Internet and the compassion and heart to give it to the people. I love ThreeFold's vision and mission and I'm thrilled to be able to be a part of it."
function = "Ambassador"
linkedin= "https://www.linkedin.com/in/michael-gaffney-69b58369/"
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "American"
