full_name = "Garry Veale"
description = "Technology veteran & previous EMC EMEA Vice President - who was part of the original/founding EMC EMEA team that was recognised by for both creating a new market category & being the fastest growing technology company of the decade. Expertise around introducing and developing world class, disruptive & game changing technologies – previous experience also includes EMEA Director & VP roles at IBM, HP & Avaya - plus several tech start-ups"
why_threefold = "Sometimes in life - it's about making a stand, calling it as it is & doing the right thing. That's what the ThreeFold Foundation is about - innovation & integrity!"
function = "Ambassador"
linkedin= ""
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Welsh"
