full_name = "Roel P. Castelein"
description = "Roel is experienced in designing and executing global strategies at Microsoft, Autodesk and Dell EMC. Making organizations smarter, better adapted and more sustainable is what he loves doing. Roel is comfortable at cross roads between business and IT, using the latter to transform the first. He delivered quantifiable results in multinational environments, and ensured they were repeatable. Presently Roel is active at retailer Colruyt Group supporting them in their data-driven approach to grow both financially and sustainably. In addition Roel kindles his passion for sustainability as EMEA Marketing Chair for The Green Grid (the Greenpeace of the ICT industry)."
why_threefold = "The combination of 'resource efficient ICT' with a 'new global currency' address two of humanity's biggest challenges. How to grow sustainably both 'economically' and 'data-wise' within the limits of Earth's resources? Nobody knows. TF ambassadors attempt to tackle these challenges and spread the news."
function = "Ambassador"
linkedin= ""
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Belgian"
