full_name = "Gloria Anne"
description = "The relentlessly helpful office administrator in Mazraa, but she is also like a bookkeeper."
why_threefold = "The feeling of contributing to something larger than myself... very significant"
function = "Admin & Bookkeeping"
rank = 0
project_ids = [1,5]
contribution_ids = [3,3]
nationality = "Filipino"
