full_name = "Lee Smet"
description = "Lee is a software developer working on the TF-chain. Before ThreeFold Lee was mainly involved in the creation of Itsyou.online in his time at GIG.tech. In his spare time, Lee can be found on the soccer pitch in keeping the scoreboard against his team Sint-Anna Lokeren on a steady 0."
why_threefold = "I joined ThreeFold because I believe everyone should have access to a fair and distributed internet, and ThreeFold aims to make this a reality."
function = "Engineer"
linkedin= ""
rank = 0
project_ids = [1,2]
contribution_ids = [6,6]
nationality = "Belgian"
