full_name = "Abdelrahman Ghanem"
description = "A software engineer, mainly working on Jumpscale platform and Kosmos"
why_threefold = "Because we are doing stuff that nearly no one else is trying to do, which involves solving new challenge that i've never faced before."
function = "Engineer"
linkedin= ""
project_ids = [1,8]
contribution_ids = [6,6]
nationality = "Egyptian"
