full_name = "Andrew Ayoub"
description = "Andrew is a passionate Computer Scientist who loves exploring new areas in life and technology"
why_threefold = "because threefold the future of technology"
function = "Engineer"
rank = 0
project_ids = [1,2]
contribution_ids = [6,6]
nationality = "Egyptian"
