full_name = "Maxime Daniel"
description = "C, python and nodejs developer, Gentoo user, Linux and Music addict"
why_threefold = "ThreeFold push the world, in my opinion, in the right direction of free, decentralized and openminded internet for everyone. I'm really happy to be part of this project which can change the world !"
function = "Engineer"
linkedin= "https://www.linkedin.com/in/maxime-daniel-29bb8055/"
rank = 0
project_ids = [1,2]
contribution_ids = [6,6]
nationality = "Belgian"
