full_name = "Souvik Ghosh"
description = """I have been working in the financial industry mainly IT as engineer, architect and more recently 
as AI/ML engineer. I am passionate about technology and along with my day-job, i am also working 
as a freelance ML specialist under the name strai.be """
why_threefold = """The technology behind threefold is convicing and 
the mission to build more user-centric internet. 
Most importantly, I am originally from India and i 
understand fully why access to free internet is a 
fundamental human right and what information 
warfare can do to a country. Threefold is on a mission
 to make it right and it would be an honour to be part 
of such a mission. My contributions will be mostly
 technical coming from a world of analytics and 
working on Natural Language Processing for past 
2 years dedicated a good amount of my time 
building open-source products. My contribution for 
the moment will be focussed around 3bot."""
function = "ThreeFold Foundation"
linkedin= "https://www.linkedin.com/in/souvik-ghosh-aaa30470/"
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Belgian"
