full_name = "Olivia Kemp"
description = "After completing school and sports education (focus on skiing, swimming, volleyball) I had various international assignments and education (Stanford, South Africa) and am now completing my master studies in economics and law. In addition I work at a law firm in Vienna and have occasional hosting assignments at Red Bull Racing."
why_threefold = "I believe in the ThreeFold Token Foundation because I am one of the first generations growing up with the internet. However, current developments show, companies are making internet users very dependent on all their technologies. So as I see it, an opportunity to have alternative ways of providing cyber space without contributing to the „vitreous human“, will be a major stepping stone."
function = "Ambassador"
linkedin= "https://www.linkedin.com/in/olivia-kemp-810a419a/"
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Austrian, British"
