full_name = "Erik de Rijk"
description = "Erik fell in love with Unix/Linux/Open Source in 1989 on his Highschool and it never left him. His passion is programming (Shell, php, C and C++) but last few years barely been able to sit behind a Linux terminal to write some proper code (although his hands are itching whenever he sees the crap that is floating out there). Co-founded Unix Support Nederland (USN) with 8 other students and now co-founder and head of a Linux consultancy company (Proxy) with 50 highly qualified Unix/Linux/Open Source technicians in the Netherlands (who call themselves Nerds...)."
why_threefold = "After the software/OS revolution that Linux invoked, we need a similar revolution in compute and storage and the ThreeFold foundation may be the spark we need to start this."
function = "Ambassador"
linkedin= ""
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Dutch"
