full_name = "Sasha Astiadi"
description = "Sasha is a principal product manager with a strong emphasis in UX Research and Human-Computer Interaction. It is her duty and aspiration to define the ways humans relate to and interact with the planet and create a better-designed world. With her multilingual skills of Indonesian, English, Chinese, German and Spanish, she has transformed products into the betterment for clients such as VW, Goethe Institute, Audi, Mozilla, Porsche, Nokia, Here Technologies, and worked globally in Germany, China, Indonesia, Spain, and the USA in the digital product management and user experience sphere."
why_threefold = "With a unique, realistic, and achievable solution to building a green, decentralised, distributed, and neutral IT infrastructure globally, committed to true values and charity, how can anyone not believe in the ThreeFold Foundation vision ?"
function = "Product Coordinator"
linkedin= "https://www.linkedin.com/in/sastiadi/"
rank = 0
project_ids = [1]
contribution_ids = [1,3]
nationality = "Indonesian"
