full_name = "Dylan Verstraete"
description = "Coffee drinking cat lover that commits code to multiple projects within the Threefold Ecosystem. Has a passion for wakeboarding and webtechnologies."
why_threefold = "I want to be a part of this digital shift."
function = "Engineer"
linkedin= "https://www.linkedin.com/in/dylan-verstraete-229539a4/"
rank = 0
project_ids = [1,2]
contribution_ids = [6,6]
nationality = "Belgian"
