full_name = "Ahmed Hanafy"
description = "Ahmed is an Automation Software Testing Engineer, started his carreer at Codescalers, and now has about a year experience in Cloudcomputing software."
why_threefold = "I believe that Threefold is changing the world by building the new neutral internet, it's a great experience to be part of this."
function = "Engineer"
rank = 0
project_ids = [1,8]
contribution_ids = [6,6]
nationality = "Egyptian"
