full_name = "Erwin Raets"
description = "Erwin has always been interested by the latest technologies, and always eager to try out the latest crazy things. He worked in the entertainment business, autosports, as a software developer and architect, and currently also running a company that provides charging solutions for electric cars. He came to realize in the past few years that we as humans need to address some very important issues to make sure we don’t ruin our planet in front of our grandchildren. That is why he want to help focus on making effective use of energy resources and fine-tuning the capture and storage of green energy."
why_threefold = "I strongly believe that blockchain technology will bring about big changes in the foreseeable future, and what the ThreeFold Foundation has set forth as goals, and the way they want to do it, has my full support.The edge computing backbone combined with a value-backed token will provide a solid foundation to expand the internet to those that currently have no access to the world’s information highway."
function = "Ambassador"
linkedin= ""
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Belgian"
