full_name = "Ahmed Siddique"
description = "A  hardworking individual and a casual guy who loves to explore new ideas in Tech. Experience in Telecom/IT, Networks, Cloud and  Systems Engineering and Servers Administration. I enjoy learning new things as Learning never exhausts the mind"
why_threefold = "I have not yet come accross an organization who are rebuilding the entire ecosystem of how things work in Tech. ThreeFold is going to be huge and i want to make sure i was part of this great movement."
function = "Engineer"
linkedin= ""
project_ids = [1,5]
contribution_ids = [6,6]
nationality = "UAE"
