full_name = "Wieger Atsma"
description = "Wieger have been working for several companies in the field of communications and advertising for over 20 years. It taught him to look at details, while keeping an eye on the big picture. His aim is to never fully grow up, and to never stop wondering. By connecting people, humor, ideas and an open mind, he believes anything is possible."
why_threefold = "The ThreeFold Foundation combines several core values that I hold dear, connecting people in a meaningful way by means of state-of-the-art blockchain technology. I believe internet access should be available for all, without straining the planet’s resources. Sustainable internet for all just makes sense to me."
function = "Ambassador"
linkedin= ""
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Dutch"
