full_name = "Dina Abdelrahman"
description = "Dina 1 year experience in CloudComputing, getting her Bachelor degree in Communication Engineer Free time = Reading, Cooking, watching movies and keep in touch with technology"
why_threefold = "I believe in ThreeFold goals and ideas. Plus, it has lots of bright minds I'm so proud to work/learn from them on a daily basis."
function = "Engineer"
rank = 0
project_ids = [1,8]
contribution_ids = [6,3]
nationality = "Egyptian"
