full_name = "Andreas Hartl"
description = "Establishing new brands and building solid successful teams have been Andreas passion for more than 15 years. He held several senior roles at major ICT firms in both global and regional management responsibilities. Andreas was the Head of Global Channel Sales at GIG Technology, a technology company at the forefront of distributed IT infrastructure. Prior to this Andreas spent eight years at Riverbed in numerous senior roles including Regional Head for Germany, Austria and Switzerland and also EMEA Head of Channel Sales. Andreas has a strong track record of developing and executing business strategies and delivering revenues in new markets. He has a degree in Business Economics from the University of Regensburg in Regensburg, Germany."
why_threefold = ""
function = "Co-Founder"
rank = 6
project_ids = [2]
contribution_ids = [1]
nationality = "German"
