full_name = "Gregor Sideris"
description = "Gregor lives in Vienna, Austria and is currently a Digital Marketing Manager responsible for Social Media at IBM Central Europe Region headquarters. Since 2009 Gregor is very active in Social Media where he now reaches over 8 million people every month and runs a successful Lifestyle Blog (www.theviennablog.com). As one of the leading Tech & Lifestyle Influencer in Europe he is often invited as a consultant and public speaker."
why_threefold = "I am sure the concept and strategy of ThreeFold is exactly what the world/markets needs now. Most importantly I believe in the people and Ambassadors who are part of the movement/mission."
function = "Ambassador"
linkedin= ""
rank = 0
project_ids = [1,2]
contribution_ids = [2,5]
nationality = "Austrian"
