full_name = "Tobias chielens"
description = "Tobias is a passionate developer that wants to use technology to make the world a better place"
why_threefold = "Creating an internet that is accessible for everyone"
function = "Developer"
linkedin= "https://www.linkedin.com/in/tobiaschielens/"
project_ids = [2,9,17]
contribution_ids = [6]
nationality = "Belgian"
