full_name = "Katja Luik"
description = "44 years, living close to Stuttgart in Germany. Almost 20 years professional experiences at Hewlett Packard Enterprise in various EMEA Business Unit and Supply Chain Finance/Controlling functions for the Storage and Servers Business segment. Enjoy a GAP Year since May 2018, with focus on social engagement and a growing interest in new technologies and markets (…but still not a tech Lady :-) )."
why_threefold = "I believe the world needs positive changes - end to end- the way we communicate, the way we support each other, the way we care - in all aspects of life - including the IT side. TF has a great approach - and I’m excited to get closer into the TF mission. Therefore- THANK YOU Owen and Peter for the chance to gather more insight about TF technology and the people involved."
function = "Ambassador"
linkedin= ""
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "German"
