full_name = "Dina Magdy"
description = "Dina Magdy is working as an Automation Software Testing Engineer, starting her carreer at codescalers , and now has about 2 year experience in cloudcomputing software ."
why_threefold = "Threefold create future internet,so it amazing to be part of this"
function = "Engineer"
linkedin= "https://www.linkedin.com/in/dina-magdy/"
rank = 0
project_ids = [1,8]
contribution_ids = [6,3]
nationality = "Egyptian"
