full_name = "Ivan Coene"
description = "Front-end developer at Jimber"
why_threefold = ""
function = "Front-end developer"
linkedin= "https://www.linkedin.com/in/ivancoene/"
project_ids = [9]
contribution_ids = [6]
nationality = "Belgian"
