full_name = "Maximilian Rang"
description = "Maximilian worked as Creative Director with six years of experience in motion and brand design for top 100 brands. Companies such as Audi and Porsche entrusted him with world premieres of their products. His passion for & p2p technology lead him to work with many startups in the decentralized space. He then joined ThreeFold only a few days after he learned about the project, because its so much aligned with this vision of how the Internet should be working for everyone."
function = "Marketing & Communication"
linkedin= "https://www.linkedin.com/in/maximilian-rang"
rank = 0
project_ids = [1,12]
contribution_ids = [1,3]
nationality = "German"
