full_name = "Ahmed Odeh"
description = "Ahmed is a legal consultant specializing in civil & criminal dispute resolution in the UAE. Areas of practice also include commercial, real estate, arbitration and labour. Ahmed also has showcased proven results in managing legal teams in litigation and corporate services, fostering teamwork for projects such as due diligence and client reporting. He is also the author of knowyourrights.dubizzle.com"
why_threefold = "I believe that ThreeFold token will be the leading digital currency as it has a clear vision to utilise the best of blockchain technology to deliver IT capacity to everyone around the world"
function = "Ambassador"
linkedin= "https://www.linkedin.com/in/ahmed-odeh-615a9740/"
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Jordanian"
