full_name = "Ramez Saeed"
description = "Ramez has about 10 years of experience in CloudComputing software. He joined Kristof and his team on 2008, Started in Q-layer, Amplidata, GiG and currently TFtech. Currently Ramez is working as a quality control and operations teamleader."
why_threefold = "Threefold is the upcoming internet future, we are creating conscious futures together"
function = "Engineer"
linkedin= ""
rank = 0
project_ids = [1,8]
contribution_ids = [6,6]
nationality = "Egyptian"
