full_name = "Frederico Fumagalli"
description = "Federico,46, holds a Bachelor in Economy and an Executive Management certificate at SDA Bocconi. After having spent 10+ in IT, Federico served for several years a multinational company active in machines industry where he’s been engaged in different executive management positions. Actually, Federico is COO of an innovative Swiss Biomedical company and actively engaged in other innovative and edge-technology initiatives."
why_threefold = "I firmly believe that TFF fills at the best the huge mid-long term gap between availability and demand for one of the key resources: IT capacity. I share the vision of granting whoever and wherever a fair priced, nature friendly and close-by internet capacity. TFF is backed not only with assets but with the right core human values."
function = "Ambassador"
linkedin= ""
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Italian"
