full_name = "Benjelloun Oussama"
description = "Oussama is a globetrotter that advocates for equality and inclusive communities around the world. He is an early cryptocurrency activist who has lead teams at startups in Silicon Valley, China, and Singapore, with a mission to make the world a happier place one smile at a time." 
why_threefold = "ThreeFold's P2P internet is exactly what humans need in order to create decentralized and inclusive communities around the globe, and empower developers to decentralize their IT infrastructures."
function = "Blockchain Ecosystem development Lead"
linkedin= "https://www.linkedin.com/in/oussama-benjelloun-110b51128/"
project_ids = [1]
contribution_ids = [1]
nationality = ""
