full_name = "Chris Hurd"
description = "A graduate of Cambridge University, Chris has spent most of his career to date in the financial services sector, with the last 20 years spent in senior banking roles in London, Singapore and Moscow. These and other previous positions have contributed to a rich and varied set of skills and experience which he is now deploying in the non-executive and advisory spheres. In this context, the aims of ThreeFold Foundation are both close to his heart and offer the opportunity for him to make a strong contribution and impact. Chris is married with 3 children and currently resides in the UK, but travels widely and maintains strong ties with Asia in particular. He greatly enjoys working with people and exploring new interests and cultures."
why_threefold = "ThreeFold Foundation offers new channels of access and investment to a very diverse audience and so deserves to succeed. It is a step into the future whose potential for good knows no boundaries"
function = "Ambassador"
linkedin= "https://www.linkedin.com/in/chris-hurd-29a5581b/"
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "British"
