full_name = "Geert Machtelinckx"
description = "Geert has 24 years of experience in IT of a Belgian financial institution, and is passionate about new technologies such as AI and blockchain."
why_threefold = "With digitisation and blockchain, the world is changing. I believe that doing it the ThreeFold way, the world will change according to the true spirit of blockchain, enabling a real decentralisation and bringing more equality. Moreover, having internet capacity used as a real world value backing and a monetary instrument, ThreeFold can make the bridge between the cryptoworld and the ‘old’ world."
function = "Project Coordination"
linkedin= ""
rank = 0
project_ids = [1]
contribution_ids = [1]
nationality = "Belgian"
