full_name = "Erik Reitsma"
description = "Erik is an entrepreneur and designer from Holland. Together with his companions he loves to invent, create and make things possible. By looking at things from another perspective they reinvent reality. That is how unexpected but often simple solutions arise on things such as one's own pension fund, circulair material use and sharing-projects. To be able to accomplish things, he strongly believes in keeping things simple and bringing people together."
why_threefold = "I love the TFF’s decentralized solution for the future of internet and like to help making it a reality for everyone in any way i can."
function = "Ambassador"
linkedin= ""
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Dutch"
