full_name = "Yves Kerwyn"
description = "Proud ThreeFold Ambassador"
why_threefold = "The internet should treated as a human right for all, and I love contributing to a goal that would make this possible."
function = "Ambassador"
linkedin= "https://www.linkedin.com/in/yveskerwyn/"
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Belgian"
